### ISSUE TITLE
Генерація посилань в маркдауні працює некоректно?

### ISSUE THREAD

**Issue by AdriandeCita** [webdoky/platform-next#12]
![image](https://user-images.githubusercontent.com/11510394/152972542-eb31124e-5116-4395-87c3-0354789cd2b4.png)

https://webdoky.org/uk/docs/Web/JavaScript/Reference/Global_Objects/Promise#zviazani-promisy

**Comment by undead404** [comment]
та сама проблема? https://webdoky.org/uk/docs/Web/CSS/Reference/#holovni-typy-obiektiv

**Comment by undead404** [comment]
![IMAGE 2022-10-04 12:18:04](https://user-images.githubusercontent.com/22787669/193782923-f7a6f74f-37f8-4088-99f2-6343c77e2470.jpg)

**Comment by AdriandeCita** [comment]
Рушій працює коректно. Логіка роботи така, що спершу ми розгортаємо макроси, а лише потім - компілюємо маркдаун. Така послідовність - це історичне рішення іншої проблеми, пов'язаної з колізіями маркдаун-синтаксису, яка призводила ламання деяких макросів до їх розгортання. https://github.com/webdoky/platform/issues/60

Єдине притомне рішення, яке я зараз бачу - це оформити макроси як розширення синтаксиса маркдауна. Але це поки неясно з точки зору реалізації

**Comment by AdriandeCita** [comment]
Спробував просто дозволити html всередині вбудованих блоків коду [feat: add support for htm tags inside inline code blocks](https://github.com/webdoky/content-processor/commit/9d1048787a6a7dc5fec9f29fb2e8978ed0d1f6ea)

На жаль, хоча це дає змогу зробити посилання робочими, це також ламає інші вбудовані кодові елементи.
**До:**
![image](https://user-images.githubusercontent.com/11510394/197385438-bdae6fe8-e0bf-4c5c-aae6-799dc990028a.png)
**Після:**
![image](https://user-images.githubusercontent.com/11510394/197385444-5bb8cc61-c799-4460-bf81-9b73420d90fa.png)

**Comment by AdriandeCita** [comment]
отже, реалізація повинна відповідати десь таким вимогам:
- макроси повинні виконуватися **після** трансформації маркдауна в HTML (після завершення роботи `remark-rehype`).
- також макроси повинні виконуватися **до** основних HTML-трансформацій (ну наприклад щоб в макросах тех правльно зовнішні посилання підсвічувалися).
- макроси повинні розпізнаватися на етапі розпізнавання синтаксису маркдауна, аби це їх не ламало

**Comment by AdriandeCita** [comment]
https://github.com/webdoky/content-processor/tree/feat/move-macros-into-markdown-syntax

**Comment by undead404** [comment]
Ніби все ок уже
