### ISSUE TITLE
Приховувати директиви Markdownlint зі сніпетів

### ISSUE THREAD

**Issue by undead404** [webdoky/platform-next#22]
![Screenshot 2022-10-14 at 10 24 39](https://user-images.githubusercontent.com/22787669/195787316-0423ba94-0849-45ef-94f2-a785f4e44e6f.png)

**Comment by AdriandeCita** [comment]
Виправлено тут [feat: exclude comments from code samples](https://github.com/webdoky/content-processor/commit/86026ed0268b7949e7e04b34e222a408f311250d)
